name: 'Github Follows & Unfollows Automation Bot'
description: 'Features unfollow all non-followers of the owner and follow back those who the owner was not following.'
author: 'Huniko519'

inputs:
  token:
    description: 'The token used to authenticate.'
    required: true
    default: ${{ github.token }}

  repository:
    description: 'The name of the repository.'
    required: true
    default: ${{ github.repository }}

  isReadmeUpdate:
    description: 'Readme update enable status.'
    required: false
    default: ${{ github.isReadmeUpdate }}

  safeUserList:
    description: 'Lists of Safe Users.'
    required: false
    default: ${{ github.safeUserList }}

  isEnableFollow:
    description: 'Enable Follow'
    requried: false
    default: true

  isEnableUnfollow:
    description: 'Enable Unfollow'
    required: false
    default: true

runs:
  using: 'node20'
  main: 'main.js'

branding:
  icon: 'star'
  color: 'yellow'
