name: 'Github-Auto-Follow-Unfollow-View-User-List'
description: 'GitHub Action automatically creates or updates Readme with users(unfollowers, unfollowing, followers, followings) list and current user information.'
author: 'Huniko519'

inputs:
  token:
    description: 'The token used to authenticate.'
    required: true
    default: ${{ github.token }}

  username:
    description: 'The base user name.'
    required: true
    default: ${{ github.actor }}

  repository:
    description: 'The name of the repository.'
    required: true
    default: ${{ github.repository }}
    
runs:
  using: 'node16'
  main: 'main.js'

branding:
  icon: 'check-square'
  color: 'green'
